name: ssi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - pyserial
  - matplotlib
  - jupyter
  - pip
  - pip:
      - pyqtgraph
      - neurokit2
